Repository ballerina-platform/ballerina-distribution, pull requests merged in 2020-09, with the labels that each got.

#774 Add the "meta.json" File to the "/examples" Folder
  examples/meta.json
Labels: Type/Docs

#791 Migrate to new class/object defn syntax
  examples/abstract-objects/abstract_objects.bal
  examples/any-type/any_type.bal
  examples/basic-documentation/basic_documentation.bal
  examples/iterable-objects/iterable_objects.bal
  examples/log-api/log_api.bal
  examples/object-assignability/object_assignability.bal
  examples/object-initializer/object_initializer.bal
  examples/object-methods/object_methods.bal
  examples/object-type-reference/object_type_reference.bal
  examples/objects/objects.bal
  examples/readonly-objects-and-fields/readonly_objects_and_fields.bal
  examples/retry-transactions/retry_transactions.bal
  examples/testerina-assertions/testerina_assertions.bal
Labels: Area/Language

#765 [DO NOT MERGE] - Add the BBE and API Guidelines Doc
  doc-guidelines.md
  images/bal-file-comment.png
  images/bbe-comment.png
  images/bbe-folder-structure.png
  images/comments-length.png
  images/max-char-count.png
  images/mulitple-bal-files.png
  images/service-examples.png
Labels: Type/Docs

#798 Fix Issues in the Guidelines Doc
  doc-guidelines.md
Labels: Type/Docs

#801 Improve the Doc Guidelines
  doc-guidelines.md
Labels: Type/Docs

#804 Add a test to check the existance of the Email library
  stdlib-integration-tests/email/tests/email_test.bal
  stdlib-integration-tests/index.json
Labels: Type/Improvement

#812 Fix BBEs for object field `readonly` to `final` changes
  examples/index.json
  examples/object-final-fields/object_final_fields.bal
  examples/object-final-fields/object_final_fields.description
  examples/object-final-fields/object_final_fields.out
  examples/readonly-objects-and-fields/readonly_objects_and_fields.bal
  examples/readonly-objects-and-fields/readonly_objects_and_fields.description
  examples/readonly-objects/readonly_objects.bal
  examples/readonly-objects/readonly_objects.description
  examples/readonly-objects/readonly_objects.out
Labels: Area/Language

#828 Add a BBE for isolated functions
  examples/index.json
  examples/isolated-functions/isolated_functions.bal
  examples/isolated-functions/isolated_functions.description
  examples/isolated-functions/isolated_functions.metatags
  examples/isolated-functions/isolated_functions.out
Labels: Area/Language

#849 Fix Object API Docs Links in BBEs
  examples/csv-io/csv_io.bal
  examples/http-caching-client/http_caching_client.bal
  examples/http-client-endpoint/http_client_endpoint.bal
  examples/http-cookies/cookie_server.bal
  examples/http-filters/http_filters.bal
  examples/http-streaming/http_streaming.bal
  examples/http-to-websocket-upgrade/http_to_websocket_upgrade.bal
  examples/request-with-multiparts/request_with_multiparts.bal
  examples/response-with-multiparts/response_with_multiparts.bal
  examples/task-scheduler-timer/task_scheduler_timer.description
  examples/websocket-cookie/upgrade_service.bal
  examples/websub-hub-client-sample/publisher.bal
  examples/websub-internal-hub-sample/publisher.bal
Labels: Type/Docs

#850 Update on fail bbe test
  examples/different-payload-types/different_payload_types.bal
  examples/error-handling-at-single-place/error_handling_in_single_place.bal
  examples/error-handling-at-single-place/error_handling_in_single_place.description
  examples/error-handling-at-single-place/error_handling_in_single_place.metatags
  examples/error-handling-at-single-place/error_handling_in_single_place.out
  examples/error-handling-at-single-place/tests/error_handling_in_single_place_test.bal
  examples/error-handling-in-single-place/tests/error_handling_in_single_place_test.bal
  examples/header-based-routing/header_based_routing.bal
  examples/http-1-1-to-2-0-protocol-switch/http_1_1_to_2_0_protocol_switch.bal
  examples/http-100-continue/http_100_continue.bal
  examples/query-path-matrix-param/query_path_matrix_param.bal
  examples/websocket-chat-application/websocket_chat_application.bal
Labels: Type/Docs

#853 Fix an API Docs Link in a BBE
  examples/websocket-cookie/websocket_cookie.bal
Labels: Type/Docs
