Repository ballerina-platform/ballerina-distribution, pull requests merged in 2020-10, with the labels that each got.

#857 Fix the JDBC/MySQL Driver Path
  examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.description
  examples/jdbc-execute-operation/jdbc_execute_operation.description
  examples/jdbc-query-operation/jdbc_query_operation.description
  examples/mysql-batch-execute-operation/mysql_batch_execute_operation.description
  examples/mysql-call-stored-procedures/mysql_call_stored_procedures.description
  examples/mysql-complex-type-queries/mysql_complex_type_queries.description
  examples/mysql-execute-operation/mysql_execute_operation.description
  examples/mysql-init-options/mysql_init_options.description
  examples/mysql-parameterized-query/mysql_parameterized_query.description
  examples/mysql-query-operation/mysql_query_operation.description
Labels: Type/Docs

#867 Improve the ".out" file Description of the Config BBE
  examples/config-api/config_api.out
Labels: Type/Docs

#879 Remove "Observability" BBEs for SLP5
  examples/index.json
Labels: Type/Docs

#886 Add back missing java arrays example
  examples/index.json
Labels: Area/Language

#889 Fix a Typo in the config API BBE
  examples/config-api/config_api.out
Labels: Type/Docs, swan-lake-docs

#893 Add FTP module to distribution
  build.gradle
  gradle.properties
Labels: Type/New Feature

#888 Update BBEs
  examples/checkpanic/checkpanic.out
  examples/isolated-functions/isolated_functions.bal
  examples/isolated-functions/isolated_functions.description
Labels: Area/Language

#896 Add a simple FTP module test to test the existence of the FTP module
  stdlib-integration-tests/ftp/tests/ftp_test.bal
Labels: Type/Improvement

#911 Fix the "getCookie" Link in the Websocket Cookie BBE
  examples/websocket-cookie/websocket_cookie.bal
Labels: Type/Docs, swan-lake-docs

#847 Add integration test for messaging modules (rabbitmq, nats and kafka)
  ballerina/build.gradle
  stdlib-integration-tests/index.json
  stdlib-integration-tests/kafka/tests/client_tests.bal
  stdlib-integration-tests/kafka/tests/docker-compose.yaml
  stdlib-integration-tests/kafka/tests/test_utils.bal
  stdlib-integration-tests/nats/tests/pub_sub_tests.bal
  stdlib-integration-tests/rabbitmq/tests/pub_sub_tests.bal
Labels: Type/Improvement

#860 Update NATS examples
  examples/nats-basic-client/publisher.bal
  examples/nats-basic-client/publisher.out
  examples/nats-basic-client/subscriber.bal
  examples/nats-basic-client/subscriber.out
  examples/nats-streaming-client/publisher.bal
  examples/nats-streaming-client/publisher.out
  examples/nats-streaming-client/subscriber.bal
  examples/nats-streaming-client/subscriber.out
  examples/nats-streaming-consumer-with-data-binding/publisher.bal
  examples/nats-streaming-consumer-with-data-binding/publisher.out
  examples/nats-streaming-consumer-with-data-binding/subscriber.bal
  examples/nats-streaming-consumer-with-data-binding/subscriber.out
  examples/nats-streaming-durable-subscriptions/publisher.bal
  examples/nats-streaming-durable-subscriptions/publisher.out
  examples/nats-streaming-durable-subscriptions/subscriber.bal
  examples/nats-streaming-durable-subscriptions/subscriber.out
  examples/nats-streaming-queue-group/publisher.bal
  examples/nats-streaming-queue-group/publisher.out
  examples/nats-streaming-queue-group/queue-group.bal
  examples/nats-streaming-queue-group/queue-group.out
  examples/nats-streaming-start-position/publisher.bal
  examples/nats-streaming-start-position/publisher.out
  examples/nats-streaming-start-position/subscriber.bal
Labels: Type/Improvement
