Repository ballerina-platform/ballerina-distribution, pull requests merged in 2020-06, with the labels that each got.

#526 Update messaging examples
  examples/all-bbes.json
  examples/kafka-authentication-sasl-plain-consumer/kafka-authentication-sasl-plain-consumer.metatags
  examples/kafka-authentication-sasl-plain-producer/kafka-authentication-sasl-plain-producer.metatags
  examples/kafka-consumer-client/kafka-consumer-client.metatags
  examples/kafka-consumer-group-service/kafka-consumer-group-service.metatags
  examples/kafka-consumer-service/kafka-consumer-service.metatags
  examples/kafka-producer-transactional/kafka-producer-transactional.metatags
  examples/kafka-producer-transactional/kafka_producer_transactional.bal
  examples/kafka-producer/kafka-producer.metatags
  examples/nats-basic-client/nats-basic-client.metatags
  examples/nats-streaming-client/nats-streaming-client.metatags
  examples/nats-streaming-consumer-with-data-binding/nats-streaming-consumer-with-data-binding.metatags
  examples/nats-streaming-consumer-with-data-binding/publisher.bal
  examples/nats-streaming-durable-subscriptions/nats-streaming-durable-subscriptions.metatags
  examples/nats-streaming-queue-group/nats-streaming-queue-group.metatags
  examples/nats-streaming-start-position/nats-streaming-start-position.metatags
  examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq-consumer-with-client-acknowledgement.metatags
  examples/rabbitmq-consumer-with-data-binding/rabbitmq-consumer-with-data-binding.metatags
  examples/rabbitmq-consumer-with-data-binding/rabbitmq_consumer_with_data_binding.bal
  examples/rabbitmq-consumer-with-qos-settings/rabbitmq-consumer-with-qos-settings.metatags
  examples/rabbitmq-consumer/rabbitmq-consumer.metatags
  examples/rabbitmq-producer/rabbitmq-producer.metatags
  examples/rabbitmq-transaction-consumer/rabbitmq-transaction-consumer.metatags
  examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal
  examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.description
  examples/rabbitmq-transaction-producer/rabbitmq-transaction-producer.metatags
  examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.bal
  examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.description
Labels: Type/Docs

#519 Add API Doc Links in the Crypto BBE
  examples/crypto/crypto.bal
Labels: Type/Docs

#546 Update BBEs for Email Connector for Ballerina 2.0
  examples/send-and-receive-emails/send_and_receive_emails.metatags
  examples/send-and-receive-emails/send_and_receive_emails_1_smtp.bal
  examples/send-and-receive-emails/send_and_receive_emails_2_pop.bal
  examples/send-and-receive-emails/send_and_receive_emails_3_imap.bal
  examples/send-and-receive-emails/send_and_receive_emails_4_listener.bal
  examples/send-and-receive-emails/send_and_receive_emails_4_listener.out
Labels: Type/Docs

#565 Fix JSON/Record/Map Conversion sample
  examples/json-record-map-conversion/json_record_map_conversion.bal
Labels: Area/Language

#563 Update details of BBE : Objects can now refer non-abstract objects
  examples/object-type-reference/object_type_reference.bal
  examples/object-type-reference/object_type_reference.description
Labels: Area/Language

#577 Update deprecation BBE test case ouput
  examples/deprecation/deprecation.out
Labels: Area/Language

#591 Remove binding patters from let-expression BBE
  examples/let-expression/let_expression.bal
  examples/let-expression/let_expression.out
Labels: Area/Language

#559 Update BBEs for `readonly` type and fix a few BBEs
  examples/all-bbes.json
  examples/equality/equality.bal
  examples/equality/equality.description
  examples/immutable-values/immutable_values.bal
  examples/immutable-values/immutable_values.description
  examples/immutable-values/immutable_values.out
  examples/immutable-values/tests/immutable_values_test.bal
  examples/readonly-type/readonly_type.bal
  examples/readonly-type/readonly_type.description
  examples/readonly-type/readonly_type.out
  examples/readonly-type/tests/readonly_type_test.bal
  examples/type-cast/tests/type_cast_test.bal
  examples/type-conversion/tests/type_conversion_test.bal
  examples/type-conversion/type_conversion.bal
  examples/type-conversion/type_conversion.description
Labels: Area/Language

#548 Add raw template BBE
  examples/all-bbes.json
  examples/raw-template/raw_template.bal
  examples/raw-template/raw_template.description
  examples/raw-template/raw_template.metatags
  examples/raw-template/raw_template.out
Labels: Area/Language, Type/Docs, Type/New Feature

#590 Add BBEs for readonly objects and readonly record/object fields
  examples/all-bbes.json
  examples/readonly-objects-and-fields/readonly_objects_and_fields.bal
  examples/readonly-objects-and-fields/readonly_objects_and_fields.description
  examples/readonly-objects-and-fields/readonly_objects_and_fields.out
  examples/readonly-objects-and-fields/tests/readonly_objects_and_fields_test.bal
  examples/record-readonly-fields/record_readonly_fields.bal
  examples/record-readonly-fields/record_readonly_fields.description
  examples/record-readonly-fields/record_readonly_fields.out
  examples/record-readonly-fields/tests/record_readonly_fields_test.bal
Labels: Area/Language

#586 Fix and align error related BBEs
  examples/check/tests/check_test.bal
  examples/checkpanic/tests/checkpanic_test.bal
  examples/error-handling/error_handling.bal
  examples/error-handling/error_handling.description
  examples/error-handling/error_handling.out
  examples/error-handling/tests/error_handling_test.bal
  examples/panic/panic.bal
  examples/panic/panic.out
  examples/panic/tests/panic_test.bal
  examples/trap/trap.bal
  examples/trap/trap.description
  examples/user-defined-error/tests/user-defined-error.bal
  examples/user-defined-error/user_defined_error.bal
  examples/user-defined-error/user_defined_error.description
  examples/user-defined-error/user_defined_error.out
Labels: Area/Language

#576 Fix function related BBEs
  examples/anonymous-functions/anonymous_functions.bal
  examples/anonymous-functions/anonymous_functions.description
  examples/function-pointers/function_pointers.bal
  examples/function-pointers/function_pointers.description
Labels: Area/Language

#599 Fix suggestions for error BBEs
  examples/all-bbes.json
  examples/error-handling/error_handling.bal
  examples/trap/trap.description
  examples/user-defined-error/user_defined_error.bal
  examples/user-defined-error/user_defined_error.description
Labels: Area/Language

#600 Fix taint checking BBE
  examples/taint-checking/taint_checking.bal
  examples/taint-checking/taint_checking.out
Labels: Area/Language

#566 Add BBE for `never` type
  examples/all-bbes.json
  examples/never-type/never_type.bal
  examples/never-type/never_type.description
  examples/never-type/never_type.metatags
  examples/never-type/never_type.out
Labels: Area/Language

#608 Fix table.bal format and output
  examples/table/table.bal
  examples/table/table.out
Labels: Area/Language
