Repository ballerina-platform/ballerina-distribution, pull requests merged in 2021-03, with the labels that each got.

#1365 Add changes from API changes
  examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.bal
  examples/kafka-consumer-group-service/kafka_consumer_group_service.bal
  examples/kafka-consumer-service/kafka_consumer_service.bal
  examples/kafka-producer-transactional/kafka_producer_transactional.bal
  examples/kafka-producer/kafka_producer.bal
Labels: Priority/High

#1379 Fix central tests by removing version from executable jar
  devtools-integration-tests/src/test/java/org/ballerina/devtools/central/CentralTest.java
  devtools-integration-tests/src/test/java/org/ballerina/devtools/central/CentralTestUtils.java
Labels: Team/DevTools

#1444 Fix arrays.bal for slalpha3
  examples/arrays/arrays.bal
  examples/arrays/arrays.out
Labels: Area/Standard Libraries, Team/CompilerFE, Type/TestFailure

#1438 Fix 'testBuildAndRunPackageD' test
  devtools-integration-tests/src/test/java/org/ballerina/devtools/central/CentralTest.java
  devtools-integration-tests/src/test/resources/central/projectD/main.bal
Labels: Team/DevTools

#1461 Remove the Docker BBEs from the "index.json" File
  examples/index.json
Labels: Swan Lake - Alpha3, Type/Docs

#1463 Fix the TCP and UDP Module Links in BBEs
  examples/tcp-listener/tcp_listener.description
  examples/udp-listener/udp_listener.description
Labels: Swan Lake - Alpha3, Type/Docs, Version/SLAlpha3

#1471 Fix the Comments of the Multipart Response BBE
  examples/response-with-multiparts/response_with_multiparts.bal
Labels: Swan Lake - Alpha3, Type/Docs, Version/SLAlpha3

#1472 Update messaging examples with updates in swan lake-alpha4
  examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.bal
  examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.bal
  examples/kafka-consumer-client/kafka_consumer_client.bal
  examples/kafka-consumer-group-service/kafka_consumer_group_service.bal
  examples/kafka-consumer-service/kafka_consumer_service.bal
  examples/kafka-producer-transactional/kafka_producer_transactional.bal
  examples/kafka-producer/kafka_producer.bal
  examples/nats-basic-client/publisher.bal
  examples/nats-basic-client/subscriber.bal
  examples/nats-streaming-client/publisher.bal
  examples/nats-streaming-client/subscriber.bal
  examples/nats-streaming-durable-subscriptions/publisher.bal
  examples/nats-streaming-durable-subscriptions/subscriber.bal
  examples/nats-streaming-queue-group/publisher.bal
  examples/nats-streaming-queue-group/queue-group.bal
  examples/nats-streaming-start-position/publisher.bal
  examples/nats-streaming-start-position/subscriber.bal
  examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.bal
  examples/rabbitmq-consumer/rabbitmq_consumer.bal
  examples/rabbitmq-producer/rabbitmq_producer.bal
  examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal
  examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.bal
Labels: Priority/High

#1482 Fix line length in messaging bbes
  ballerina-test/src/test/resources/testing-line-length.xml
  examples/kafka-consumer-group-service/kafka_consumer_group_service.bal
  examples/kafka-consumer-service/kafka_consumer_service.bal
  examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.bal
  examples/rabbitmq-consumer/rabbitmq_consumer.bal
  examples/rabbitmq-producer/rabbitmq_producer.bal
  examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal
  examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.bal
Labels: Priority/High

#1509 Fix compilation errors in messaging examples
  examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.bal
  examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.bal
  examples/kafka-consumer-client/kafka_consumer_client.bal
  examples/kafka-consumer-group-service/kafka_consumer_group_service.bal
  examples/kafka-consumer-service/kafka_consumer_service.bal
  examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.bal
  examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal
Labels: Priority/High

#1495 Update Iterable Objects BBE
  ballerina/build.gradle
  examples/iterable-objects/iterable_objects.bal
  examples/iterable-objects/iterable_objects.description
  examples/iterable-objects/iterable_objects.out
Labels: Team/CompilerFE
