Repository ballerina-platform/ballerina-distribution, pull requests merged in 2023-01, with the labels that each got.

#3931 Update BBE related to `Langlib functions`
  examples/langlib-functions/langlib_functions.bal
  examples/langlib-functions/langlib_functions.md
  examples/langlib-functions/langlib_functions.out
Labels: Team/CompilerFE, Area/BBE

#3920 Add new BBEs for `main` , `init` functions
  examples/index.json
  examples/init-function/init_function.bal
  examples/init-function/init_function.md
  examples/init-function/init_function.metatags
  examples/init-function/init_function.out
  examples/main-function/main_function.bal
  examples/main-function/main_function.md
  examples/main-function/main_function.metatags
  examples/main-function/main_function.out
Labels: Team/CompilerFE, Area/BBE

#3840 Revamp Function BBEs
  examples/anonymous-function/anonymous_function.bal
  examples/anonymous-function/anonymous_function.md
  examples/anonymous-function/anonymous_function.metatags
  examples/anonymous-function/anonymous_function.out
  examples/default-values-for-function-parameters/default_values_for_function_parameters.bal
  examples/default-values-for-function-parameters/default_values_for_function_parameters.md
  examples/default-values-for-function-parameters/default_values_for_function_parameters.metatags
  examples/function-closure/function_closure.bal
  examples/function-closure/function_closure.md
  examples/function-closure/function_closure.metatags
  examples/function-closure/function_closure.out
  examples/function-pointers/function_pointers.bal
  examples/function-pointers/function_pointers.md
  examples/function-pointers/function_pointers.metatags
  examples/function-pointers/function_pointers.out
  examples/function-types/function_types.bal
  examples/function-types/function_types.md
  examples/function-types/function_types.metatags
  examples/function-types/function_types.out
  examples/function-values/function_values.bal
  examples/function-values/function_values.md
  examples/function-values/function_values.metatags
  examples/function-values/function_values.out
  examples/functions/functions.bal
  examples/functions/functions.md
  examples/functions/functions.metatags
  examples/functions/functions.out
  examples/index.json
  examples/provide-function-arguments-by-name/provide_function_arguments_by_name.bal
  examples/provide-function-arguments-by-name/provide_function_arguments_by_name.md
  examples/provide-function-arguments-by-name/provide_function_arguments_by_name.metatags
Labels: Team/CompilerFE, Area/BBE

#3937 Fix issues related to list `BBE`s
  examples/arrays/arrays.md
  examples/arrays/arrays.metatags
  examples/binary-data/binary_data.md
  examples/filler-values-of-a-list/filler_values_of_a_list.md
  examples/list-equality/list_equality.md
  examples/list-equality/list_equality.metatags
  examples/list-subtyping/list_subtyping.md
  examples/list-subtyping/list_subtyping.metatags
  examples/nested-arrays/nested_arrays.md
  examples/nested-arrays/nested_arrays.metatags
  examples/rest-type-in-tuples/rest_type_in_tuples.md
  examples/rest-type-in-tuples/rest_type_in_tuples.metatags
  examples/tuples/tuples.md
  examples/tuples/tuples.metatags
Labels: Team/CompilerFE, Area/BBE

#3877 Revamp records related BBEs
  examples/controlling-openness/controlling_openness.bal
  examples/controlling-openness/controlling_openness.md
  examples/controlling-openness/controlling_openness.metatags
  examples/controlling-openness/controlling_openness.out
  examples/default-values-for-record-fields/default_values_for_record_fields.bal
  examples/default-values-for-record-fields/default_values_for_record_fields.md
  examples/default-values-for-record-fields/default_values_for_record_fields.metatags
  examples/default-values-for-record-fields/default_values_for_record_fields.out
  examples/open-records/open_records.bal
  examples/open-records/open_records.md
  examples/open-records/open_records.metatags
  examples/open-records/open_records.out
  examples/type-inclusion-for-records/type_inclusion_for_records.bal
  examples/type-inclusion-for-records/type_inclusion_for_records.md
  examples/type-inclusion-for-records/type_inclusion_for_records.metatags
  examples/type-inclusion-for-records/type_inclusion_for_records.out
Labels: Team/CompilerFE, Area/BBE

#3948 Remove `- Ballerina by example` suffix from related links
  examples/arrays/arrays.md
  examples/binary-data/binary_data.md
  examples/filler-values-of-a-list/filler_values_of_a_list.md
  examples/list-equality/list_equality.md
  examples/list-subtyping/list_subtyping.md
  examples/nested-arrays/nested_arrays.md
  examples/rest-type-in-tuples/rest_type_in_tuples.md
  examples/tuples/tuples.md
Labels: Team/CompilerFE, Area/BBE

#3843 Add new binding patterns BBEs
  examples/binding-patterns-in-assignment/binding_patterns_in_assignment.bal
  examples/binding-patterns-in-assignment/binding_patterns_in_assignment.md
  examples/binding-patterns-in-assignment/binding_patterns_in_assignment.metatags
  examples/binding-patterns-in-assignment/binding_patterns_in_assignment.out
  examples/error-binding-pattern-in-match-statement/error_binding_pattern_in_match_statement.bal
  examples/error-binding-pattern-in-match-statement/error_binding_pattern_in_match_statement.md
  examples/error-binding-pattern-in-match-statement/error_binding_pattern_in_match_statement.metatags
  examples/error-binding-pattern-in-match-statement/error_binding_pattern_in_match_statement.out
  examples/error-binding-pattern/error_binding_pattern.bal
  examples/error-binding-pattern/error_binding_pattern.md
  examples/error-binding-pattern/error_binding_pattern.metatags
  examples/error-binding-pattern/error_binding_pattern.out
  examples/index.json
  examples/iterative-use-of-typed-binding/iterative_use_of_typed_binding.bal
  examples/iterative-use-of-typed-binding/iterative_use_of_typed_binding.md
  examples/iterative-use-of-typed-binding/iterative_use_of_typed_binding.metatags
  examples/iterative-use-of-typed-binding/iterative_use_of_typed_binding.out
  examples/mapping-binding-pattern/mapping_binding_pattern.bal
  examples/mapping-binding-pattern/mapping_binding_pattern.md
  examples/mapping-binding-pattern/mapping_binding_pattern.metatags
  examples/mapping-binding-pattern/mapping_binding_pattern.out
  examples/rest-binding-pattern-in-error-binding-pattern/rest_binding_pattern_in_error_binding_pattern.bal
  examples/rest-binding-pattern-in-error-binding-pattern/rest_binding_pattern_in_error_binding_pattern.md
  examples/rest-binding-pattern-in-error-binding-pattern/rest_binding_pattern_in_error_binding_pattern.metatags
  examples/rest-binding-pattern-in-error-binding-pattern/rest_binding_pattern_in_error_binding_pattern.out
  examples/rest-binding-pattern-in-mapping-binding-pattern/rest_binding_pattern_in_mapping_binding_pattern.bal
  examples/rest-binding-pattern-in-mapping-binding-pattern/rest_binding_pattern_in_mapping_binding_pattern.md
  examples/rest-binding-pattern-in-mapping-binding-pattern/rest_binding_pattern_in_mapping_binding_pattern.metatags
  examples/rest-binding-pattern-in-mapping-binding-pattern/rest_binding_pattern_in_mapping_binding_pattern.out
  examples/single-use-of-typed-binding/single_use_of_typed_binding.bal
  examples/single-use-of-typed-binding/single_use_of_typed_binding.md
  examples/single-use-of-typed-binding/single_use_of_typed_binding.metatags
  examples/single-use-of-typed-binding/single_use_of_typed_binding.out
  examples/single-use-with-on-fail-clause/single_use_with_on_fail_clause.bal
  examples/single-use-with-on-fail-clause/single_use_with_on_fail_clause.md
  examples/single-use-with-on-fail-clause/single_use_with_on_fail_clause.metatags
  examples/single-use-with-on-fail-clause/single_use_with_on_fail_clause.out
  examples/spread-in-binding-patterns/spread_in_binding_patterns.bal
  examples/spread-in-binding-patterns/spread_in_binding_patterns.md
  examples/spread-in-binding-patterns/spread_in_binding_patterns.metatags
  examples/spread-in-binding-patterns/spread_in_binding_patterns.out
Labels: Team/CompilerFE, Area/BBE

#3884 Revamp mappings related BBEs
  examples/computed-field-key/computed_field_key.bal
  examples/computed-field-key/computed_field_key.md
  examples/computed-field-key/computed_field_key.metatags
  examples/computed-field-key/computed_field_key.out
  examples/maps/maps.bal
  examples/maps/maps.md
  examples/maps/maps.metatags
  examples/maps/maps.out
  examples/optional-fields/optional_fields.bal
  examples/optional-fields/optional_fields.md
  examples/optional-fields/optional_fields.metatags
  examples/optional-fields/optional_fields.out
  examples/records/records.bal
  examples/records/records.md
  examples/records/records.metatags
  examples/records/records.out
Labels: Team/CompilerFE, Area/BBE

#3910 Revamp Iteration realted BBEs
  examples/break-statement/break_statement.bal
  examples/break-statement/break_statement.md
  examples/break-statement/break_statement.metatags
  examples/break-statement/break_statement.out
  examples/continue-statement/continue_statement.bal
  examples/continue-statement/continue_statement.md
  examples/continue-statement/continue_statement.metatags
  examples/continue-statement/continue_statement.out
  examples/foreach-statement/foreach_statement.bal
  examples/foreach-statement/foreach_statement.md
  examples/foreach-statement/foreach_statement.metatags
  examples/foreach-statement/foreach_statement.out
  examples/index.json
  examples/while-statement/while_statement.bal
  examples/while-statement/while_statement.md
  examples/while-statement/while_statement.metatags
  examples/while-statement/while_statement.out
Labels: Team/CompilerFE, Area/BBE

#3951 Fix the name mismatch in `index.json`
  examples/index.json
Labels: Team/CompilerFE, Area/BBE

#3955 Fix second set of issues related to list `BBEs`
  examples/arrays/arrays.bal
  examples/arrays/arrays.md
  examples/binary-data/binary_data.md
  examples/filler-values-of-a-list/filler_values_of_a_list.md
  examples/list-equality/list_equality.bal
  examples/list-equality/list_equality.md
  examples/list-subtyping/list_subtyping.bal
  examples/nested-arrays/nested_arrays.bal
  examples/nested-arrays/nested_arrays.md
  examples/rest-type-in-tuples/rest_type_in_tuples.md
Labels: Team/CompilerFE, Area/BBE

#3963 Change bal file name in md file
  examples/converting-from-json-to-user-defined-type-with-langlib-functions/converting_from_json_to_user_defined_type_with_langlib_functions.md
Labels: Team/CompilerFE

#3899 Revamp objects BBEs
  examples/client-class/client_class.bal
  examples/client-class/client_class.md
  examples/client-class/client_class.metatags
  examples/client-class/client_class.out
  examples/defining-classes/defining_classes.bal
  examples/defining-classes/defining_classes.md
  examples/defining-classes/defining_classes.metatags
  examples/defining-classes/defining_classes.out
  examples/distinct-object-types/distinct_object_types.bal
  examples/distinct-object-types/distinct_object_types.md
  examples/distinct-object-types/distinct_object_types.metatags
  examples/index.json
  examples/object-closure/object_closure.bal
  examples/object-closure/object_closure.md
  examples/object-closure/object_closure.metatags
  examples/object-closure/object_closure.out
  examples/object-constructor/object_constructor.bal
  examples/object-constructor/object_constructor.md
  examples/object-constructor/object_constructor.metatags
  examples/object-constructor/object_constructor.out
  examples/object-type-inclusion/object_type_inclusion.bal
  examples/object-type-inclusion/object_type_inclusion.md
  examples/object-type-inclusion/object_type_inclusion.metatags
  examples/object-type-inclusion/object_type_inclusion.out
  examples/object-value-from-class-definition/object_value_from_class_definition.bal
  examples/object-value-from-class-definition/object_value_from_class_definition.md
  examples/object-value-from-class-definition/object_value_from_class_definition.metatags
  examples/object-value-from-class-definition/object_value_from_class_definition.out
  examples/object/object.bal
  examples/object/object.md
  examples/object/object.metatags
  examples/object/object.out
  examples/start-service-from-service-class-definition/start_service_from_service_class_definition.bal
  examples/start-service-from-service-class-definition/start_service_from_service_class_definition.client.out
  examples/start-service-from-service-class-definition/start_service_from_service_class_definition.md
  examples/start-service-from-service-class-definition/start_service_from_service_class_definition.metatags
  examples/start-service-from-service-class-definition/start_service_from_service_class_definition.server.out
  examples/visibility-of-object-fields-and-methods/visibility_of_object_fields_and_methods.bal
  examples/visibility-of-object-fields-and-methods/visibility_of_object_fields_and_methods.md
  examples/visibility-of-object-fields-and-methods/visibility_of_object_fields_and_methods.metatags
  examples/visibility-of-object-fields-and-methods/visibility_of_object_fields_and_methods.out
Labels: Team/CompilerFE, Area/BBE

#3891 Revamp table BBEs
  examples/multiple-key-fields/multiple_key_fields.bal
  examples/multiple-key-fields/multiple_key_fields.md
  examples/multiple-key-fields/multiple_key_fields.metatags
  examples/multiple-key-fields/multiple_key_fields.out
  examples/structured-keys/structured_keys.bal
  examples/structured-keys/structured_keys.md
  examples/structured-keys/structured_keys.metatags
  examples/structured-keys/structured_keys.out
Labels: Team/CompilerFE, Area/BBE

#3850 Add new BBEs on binding patterns
  examples/binding-patterns/binding_patterns.bal
  examples/binding-patterns/binding_patterns.md
  examples/binding-patterns/binding_patterns.metatags
  examples/binding-patterns/binding_patterns.out
  examples/index.json
  examples/list-binding-pattern-in-match-statement/list_binding_pattern_in_match_statement.bal
  examples/list-binding-pattern-in-match-statement/list_binding_pattern_in_match_statement.md
  examples/list-binding-pattern-in-match-statement/list_binding_pattern_in_match_statement.metatags
  examples/list-binding-pattern-in-match-statement/list_binding_pattern_in_match_statement.out
  examples/list-binding-pattern/list_binding_pattern.bal
  examples/list-binding-pattern/list_binding_pattern.md
  examples/list-binding-pattern/list_binding_pattern.metatags
  examples/list-binding-pattern/list_binding_pattern.out
  examples/mapping-binding-pattern-in-match-statement/mapping_binding_pattern_in_match_statement.bal
  examples/mapping-binding-pattern-in-match-statement/mapping_binding_pattern_in_match_statement.md
  examples/mapping-binding-pattern-in-match-statement/mapping_binding_pattern_in_match_statement.metatags
  examples/mapping-binding-pattern-in-match-statement/mapping_binding_pattern_in_match_statement.out
  examples/rest-binding-pattern-in-list-binding-pattern/rest_binding_pattern_in_list_binding_pattern.bal
  examples/rest-binding-pattern-in-list-binding-pattern/rest_binding_pattern_in_list_binding_pattern.md
  examples/rest-binding-pattern-in-list-binding-pattern/rest_binding_pattern_in_list_binding_pattern.metatags
  examples/rest-binding-pattern-in-list-binding-pattern/rest_binding_pattern_in_list_binding_pattern.out
  examples/typed-binding-pattern/typed_binding_pattern.bal
  examples/typed-binding-pattern/typed_binding_pattern.md
  examples/typed-binding-pattern/typed_binding_pattern.metatags
  examples/typed-binding-pattern/typed_binding_pattern.out
  examples/wildcard-binding-pattern/wildcard_binding_pattern.bal
  examples/wildcard-binding-pattern/wildcard_binding_pattern.md
  examples/wildcard-binding-pattern/wildcard_binding_pattern.metatags
  examples/wildcard-binding-pattern/wildcard_binding_pattern.out
Labels: Team/CompilerFE, Area/BBE

#3968 Revamp mappings related BBEs
  examples/computed-field-key/computed_field_key.bal
  examples/computed-field-key/computed_field_key.md
  examples/computed-field-key/computed_field_key.metatags
  examples/computed-field-key/computed_field_key.out
  examples/maps/maps.bal
  examples/maps/maps.md
  examples/maps/maps.metatags
  examples/maps/maps.out
  examples/optional-fields/optional_fields.bal
  examples/optional-fields/optional_fields.md
  examples/optional-fields/optional_fields.metatags
  examples/optional-fields/optional_fields.out
  examples/records/records.bal
  examples/records/records.md
  examples/records/records.metatags
  examples/records/records.out
Labels: Team/CompilerFE, Area/BBE

#3972 Fix issues related to query expression
  examples/create-tables-with-query/create_tables_with_query.bal
  examples/let-clause/let_clause.md
  examples/querying-tables/querying_tables.bal
Labels: Team/CompilerFE, Area/BBE

#3892 Revamp XML related BBEs
  examples/index.json
  examples/xml-access/xml_access.bal
  examples/xml-access/xml_access.md
  examples/xml-access/xml_access.metatags
  examples/xml-access/xml_access.out
  examples/xml-data-model/xml_data_model.bal
  examples/xml-data-model/xml_data_model.md
  examples/xml-data-model/xml_data_model.metatags
  examples/xml-data-model/xml_data_model.out
  examples/xml-iteration/xml_iteration.bal
  examples/xml-iteration/xml_iteration.md
  examples/xml-iteration/xml_iteration.metatags
  examples/xml-iteration/xml_iteration.out
  examples/xml-mutation/xml_mutation.bal
  examples/xml-mutation/xml_mutation.md
  examples/xml-mutation/xml_mutation.metatags
  examples/xml-mutation/xml_mutation.out
  examples/xml-namespaces/xml_namespaces.md
  examples/xml-navigation/xml_navigation.md
  examples/xml-operations/xml_operations.bal
  examples/xml-operations/xml_operations.md
  examples/xml-operations/xml_operations.metatags
  examples/xml-operations/xml_operations.out
  examples/xml-subtyping/xml_subtyping.bal
  examples/xml-subtyping/xml_subtyping.md
  examples/xml-subtyping/xml_subtyping.metatags
  examples/xml-subtyping/xml_subtyping.out
  examples/xml-templates-and-query/xml_templates_and_query.md
  examples/xmlns-declarations/xmlns_declarations.md
Labels: Team/CompilerFE, Area/BBE

#3878 Revamp JSON BBEs
  examples/access-optional-json-elements/access_optional_json_elements.bal
  examples/access-optional-json-elements/access_optional_json_elements.md
  examples/access-optional-json-elements/access_optional_json_elements.metatags
  examples/access-optional-json-elements/access_optional_json_elements.out
  examples/converting-from-json-to-user-defined-type-with-langlib-functions/converting_from_json_to_user_defined_type_with_langlib_functions.bal
  examples/converting-from-json-to-user-defined-type-with-langlib-functions/converting_from_json_to_user_defined_type_with_langlib_functions.md
  examples/index.json
  examples/json-numbers/json_numbers.bal
  examples/json-numbers/json_numbers.md
  examples/json-numbers/json_numbers.metatags
  examples/resource-method-typing/resource_method_typing.bal
  examples/resource-method-typing/resource_method_typing.client.out
  examples/resource-method-typing/resource_method_typing.md
  examples/resource-method-typing/resource_method_typing.metatags
Labels: Team/CompilerFE, Area/BBE

#3956 Improve configurable BBE with new structure
  examples/configurable-variables/Config.toml
  examples/configurable-variables/configurable_variables.bal
  examples/configurable-variables/configurable_variables.md
  examples/configuring-via-cli/configuring_via_cli.bal
  examples/configuring-via-cli/configuring_via_cli.md
  examples/configuring-via-cli/configuring_via_cli.metatags
  examples/configuring-via-cli/configuring_via_cli.out
  examples/configuring-via-toml/Config.toml
  examples/configuring-via-toml/configuring-via-toml.md
  examples/configuring-via-toml/configuring_via_toml.bal
  examples/configuring-via-toml/configuring_via_toml.metatags
  examples/configuring-via-toml/configuring_via_toml.out
  examples/index.json
Labels: Team/jBallerina

#3324 Add BBE for `int:range`
  examples/index.json
  examples/int-range/int_range.bal
  examples/int-range/int_range.md
  examples/int-range/int_range.metatags
  examples/int-range/int_range.out
Labels: Team/CompilerFE

#3996 Temporary delete filler values table
  examples/filler-values-of-a-list/filler_values_of_a_list.md
Labels: Area/BBE
